name: Ep 2 test pipeline

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install lein
      id: install-lein
      run: |
        sudo apt-get update && sudo apt-get install -y leiningen

    - name: Perform test
      id: perform-test
      run: |
        cd ep2/
        lein install
        lein test